# Mise (formerly rtx) configuration
# https://mise.jdx.dev/configuration.html

# Settings section for mise configuration
[settings]
# Enable experimental features
experimental = true

# Legacy version file support
# This allows mise to read version files from other tools
legacy_version_file = true

# Jobs to run in parallel (for installations)
jobs = 4

# Plugin-specific settings
legacy_version_file_disable_tools = []

# Shorthands for common plugins - using correct syntax
[alias.node.versions]
# Support for Nodejs versions
lts = "lts/latest"
latest = "latest"

[alias.python.versions]
# Common Python versions
system = "system"

[alias.ruby.versions]
# Common Ruby versions
system = "system"

# Default tool versions (can be overridden by project-specific files)
[tools]
# These are examples - adjust to your needs
# node = "lts"
# python = "3.12"
# ruby = "3.3"
# go = "1.21"

# Environment variables
[env]
# Mise-specific environment variables
MISE_LEGACY_VERSION_FILE = "true"
MISE_ASDF_COMPAT = "true"

# Settings for specific tools
[settings]
# Configure legacy version file behavior per tool
legacy_version_file_disable_tools = []

# Plugin-specific settings
[plugins]
# Example: Configure the node plugin to use a specific mirror
# node = { mirror = "https://nodejs.org/dist" }

# Project-specific settings can be defined in .mise.toml in project root
# This global config provides sensible defaults for all projects

