#!/usr/bin/env bash
#
# The wizard library below defines a full colour set; not every wizard uses
# every colour. Left as-is deliberately: the library is identical across
# wizards and is not hand-edited.
# shellcheck disable=SC2034
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Run from anywhere: every repo path below is resolved from this script.
REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

banner "Dotfiles first run"

# ── 1. 1Password SSH agent ────────────────────────────────────────────────
stage "1Password — SSH agent"
say "Git is configured to sign every commit with an SSH key held by"
say "1Password (gpg.format=ssh, gpg.ssh.program=op-ssh-sign). Until the"
say "agent is running, every commit fails to sign."
step "Open 1Password and sign in to your account."
step "Settings -> Developer, turn on 'Use the SSH agent'."
step "Make sure the signing key is in a vault the agent can reach."
pause "Done? Press Enter to verify."
if [[ -S "${SSH_AUTH_SOCK:-}" ]]; then
  say "${GREEN}agent socket present${RESET}: $SSH_AUTH_SOCK"
else
  warn "no agent socket at SSH_AUTH_SOCK — open a new shell after enabling it"
  SKIPPED+=("1Password SSH agent — SSH_AUTH_SOCK not a socket yet")
fi
signer=$(git config --get gpg.ssh.program || true)
if [[ -n "$signer" && -x "$signer" ]]; then
  say "${GREEN}signer present${RESET}: $signer"
else
  warn "git's configured signer is missing: ${signer:-unset}"
  SKIPPED+=("1Password signer — install 1Password, or fix gpg.ssh.program")
fi
note "signing is only truly proven by a real commit; 1Password must be unlocked"

# ── 2. GitHub CLI ─────────────────────────────────────────────────────────
stage "GitHub — sign in to gh"
say "gh and gh-dash both read this login."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "${GREEN}already authenticated${RESET}"
else
  step "Run the login below and follow the browser prompts."
  say "  gh auth login"
  if confirm "Run 'gh auth login' now?"; then
    gh auth login || warn "gh auth login did not complete"
  else
    SKIPPED+=("gh auth login")
  fi
fi

# ── 3. Apple ID ───────────────────────────────────────────────────────────
stage "App Store — sign in"
say "The Brewfile has one Mac App Store entry, which needs a signed-in"
say "Apple ID. No script can do this part, and CI skips it entirely."
grep -n '^mas ' "$REPO_ROOT/Brewfile" | sed 's/^/  /' || true
step "Open the App Store and sign in with your Apple ID."
open_url "macappstore://"
pause "Signed in? Press Enter."
if command -v mas >/dev/null 2>&1 && mas account >/dev/null 2>&1; then
  say "${GREEN}signed in as${RESET} $(mas account 2>/dev/null)"
  if confirm "Install the App Store entries now with brew bundle?"; then
    brew bundle --file="$REPO_ROOT/Brewfile" || warn "brew bundle reported a problem"
  fi
else
  note "mas cannot see an account yet; re-run 'brew bundle' once signed in"
  SKIPPED+=("Mac App Store apps — sign in, then run: brew bundle")
fi

# ── 4. Karabiner-Elements ─────────────────────────────────────────────────
stage "Karabiner — build config and grant Input Monitoring"
say "The keyboard config is TypeScript that compiles to"
say "\$HOME/.config/karabiner/karabiner.json. It has to be built before"
say "Karabiner-Elements has anything to load."
if confirm "Build the Karabiner config now?"; then
  ( cd "$REPO_ROOT/karabiner" && bun install && bun run build ) || warn "karabiner build failed"
fi
step "Open Karabiner-Elements. macOS will ask for Input Monitoring."
step "Grant it for both Karabiner-Elements and karabiner_grabber."
open_url "x-apple.systempreferences:com.apple.preference.security?Privacy_ListenEvent"
pause "Granted? Press Enter."

# ── 5. yabai ──────────────────────────────────────────────────────────────
stage "yabai — accessibility and the scripting addition"
say "yabai needs Accessibility to move windows. The scripting addition,"
say "which yabairc loads with 'sudo yabai --load-sa', additionally needs"
say "SIP partially disabled and a sudoers entry."
warn "Disabling part of SIP is a security trade-off and needs a Recovery boot."
step "Grant yabai Accessibility in the pane that opens."
open_url "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"
pause "Granted? Press Enter."
say ""
say "The scripting addition steps, including the exact sudoers line, are"
say "version-specific. Follow the official wiki rather than anything typed"
say "from memory:"
open_url "https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection"
if confirm "Skip the scripting addition for now?"; then
  SKIPPED+=("yabai scripting addition — see the wiki; yabai works without it, with fewer features")
else
  pause "Press Enter when the wiki steps are done."
fi

# ── 6. Raycast ────────────────────────────────────────────────────────────
stage "Raycast — register the script directory"
say "The repo stows Raycast script commands to:"
say "  $HOME/.config/raycast/scripts"
step "Open Raycast Settings -> Extensions -> Script Commands."
step "Add Directories, and pick the path above."
open_url "raycast://extensions/raycast/raycast/settings"
pause "Added? Press Enter."

# ── 7. AWS Granted ────────────────────────────────────────────────────────
stage "AWS — populate Granted SSO profiles"
say "The 'assume' and 'granted-refresh' aliases expect Granted to know"
say "your SSO profiles."
if command -v granted >/dev/null 2>&1; then
  say "  granted sso populate --sso-region eu-west-2 https://kodehort.awsapps.com/start"
  if confirm "Populate SSO profiles now?"; then
    granted sso populate --sso-region eu-west-2 https://kodehort.awsapps.com/start \
      || warn "granted sso populate did not complete"
  else
    SKIPPED+=("granted sso populate")
  fi
else
  warn "granted is not installed — run ./install.sh first"
  SKIPPED+=("granted sso populate — granted not installed")
fi

finish
