name: Tests
on:
  push:
    branches: [main]

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Run install
        env:
          NIX_CONFIG: access_tokens=${{ secrets.GITHUB_TOKEN }}
        run: |
          bash -c "$(curl -fsSL \
          https://raw.githubusercontent.com/alistairstead/dotfiles2/main/install.sh)"
